<template>
  <ContentSection :caption="copy.caption" :title="copy.title" :content="copy.content">
    <StackedList :questions="listSteps" />
  </ContentSection>
</template>

<script lang="ts" setup>

const copy = {
  title: 'CARMA Checklist',
  caption: 'Calling in Fatigued',
  content: ['CONTACT THE COMPANY (paraphrasing CBA 12.A.9): A pilot who becomes excessively tired (fatigued) prior to or subsequent to trip shall notify CRS immediately and speak with the Duty Officer about their situation. If this happens during a trip and the decision is made to terminate the trip, the trip will end in that city. (Fatigue at domicile, during a hub turn (no legal rest between trips) is also treated as sick in the field.) 14.B.4-5 ',
    'GET REST. Work with the DO and Flight Services Desk (FSD) to arrange Ground Transportation and hotel for recovery. ',
    'DO NOT make travel arrangements until you have RESTED and RECOVERED.',
    'Fatigue in the field is treated like sick in the field (Section 14.B.4-5): “Company shall provide transportation, when the pilot is able to travel, back to his base”. If in the field, after rest, work with CRS, GT and Flight Services to deadhead back to Base. After required changes, and only then, can the crewmember deviate and make personal arrangements. (Pairing will only display activity up to fatigue call, nothing after). ',
    'Complete a Fatigue Report. An email sent to your company address will have a direct link. Secondary access is available via the PFC Report link where you will find your uncompleted report generated by the Duty Officer. '],
};

const listSteps =
  [
    { text: 'Contact the company.', caption: ' Crew Resource Scheduling', note: '1-844-495-1049' },
    { text: 'Arrange for rest - GT and hotel.' },
    { text: 'Rest and recover.' },
    { text: 'Make arrangements for return to base.' },
    { text: 'After-Action. File a fatigue report.' },
  ];

</script>
