<template>
  <div>
    <ContentSection :caption="copy.caption" :title="copy.title" :content="copy.content">
      <div class="bg-red-50 border-l-4 border-red-400 p-4 mb-6">
        <div class="flex">
          <div class="mt-2 text-sm text-red-700">
            <p class="font-bold text-lg">
              Crew Resource Scheduling: 1-844-495-1049
            </p>
            <p class="mt-1">
              For questions or concerns: FedEx-FRMC@alpa.org
            </p>
          </div>
        </div>
      </div>
      <UAccordion :items="accordionItems" variant="outline" />
    </ContentSection>
  </div>
</template>

<script lang="ts" setup>

const copy = {
  title: 'CARMA Checklist Process',
  caption: 'Step-by-Step Guide for Scenario #5 Only',
  content: ['Use this checklist ONLY when the Company removes you from the balance of your trip following a fatigue call after trip check-in.'],
};

const listSteps = [
  {
    text: 'CALL out fatigued',
    defaultOpen: true,
    caption: 'Contact CRS Immediately',
    note: '1-844-495-1049',
    popoverText: '(paraphrasing CBA 12.A.9): A pilot who becomes excessively tired (fatigued) prior to or subsequent to trip shall notify CRS immediately and speak with the Duty Officer about their situation. If this happens during a trip and the decision is made to terminate the trip, the trip will end in that city. (Fatigue at domicile, during a hub turn (no legal rest between trips) is also treated as sick in the field.) 14.B.4-5',
  },
  {
    text: 'ARRANGE for rest',
    caption: 'Work with DO and Flight Services',
    note: 'GT and hotel',
    popoverText: 'Work with the DO and Flight Services Desk (FSD) to arrange Ground Transportation and hotel for recovery. If CRS does not provide GT and Hotel, immediately call the Duty Officer.',
  },
  {
    text: 'REST and recover',
    caption: 'Priority is Rest',
    popoverText: 'DO NOT make travel arrangements until you have RESTED and RECOVERED. Your priority is rest.',
  },
  {
    text: 'MAKE ARRANGEMENTS for return to base',
    caption: 'Coordinate deadhead after rest',
    popoverText: 'Fatigue in the field is treated like sick in the field (Section 14.B.4-5): "Company shall provide transportation, when the pilot is able to travel, back to his base". If in the field, after rest, work with CRS, GT and Flight Services to deadhead back to Base. Processing should occur during your rest period, with a minimum of 8 hours after you get to the hotel. After required changes, and only then, can the crewmember deviate and make personal arrangements. (Pairing will only display activity up to fatigue call, nothing after).',
  },
  {
    text: 'AFTER-ACTION report',
    caption: 'Complete fatigue report',
    note: 'File via email link or PFC Report',
    popoverText: 'An email sent to your company address will have a direct link. Secondary access is available via the PFC Report link where you will find your uncompleted report generated by the Duty Officer.',
  },
];

const accordionItems = listSteps.map(step => ({ label: step.text, defaultOpen: step.defaultOpen, content: step.popoverText }));

</script>
