<template>
  <div>
    <ContentSection :caption="copy.caption" :title="copy.title" :content="copy.content">
      <UCard class="bg-red-50 dark:bg-red-900/20 border-l-4 border-red-500 mb-6">
        <div class="flex items-center">
          <UIcon name="i-heroicons-phone" class="h-5 w-5 text-red-600 dark:text-red-400 mr-3" />
          <div>
            <p class="text-red-800 dark:text-red-200 font-semibold">
              Crew Resource Scheduling
            </p>
            <p class="text-lg font-bold text-red-900 dark:text-red-100">
              1-844-495-1049
            </p>
          </div>
        </div>
      </UCard>
      <UAccordion :items="accordionItems" variant="outline" />
      <!--StackedList :questions="listSteps" /-->
    </ContentSection>
  </div>
</template>

<script lang="ts" setup>

const copy = {
  title: 'Calling in Fatigued',
  caption: 'CARMA Checklist',
  content: ['Any questions or concerns please email: FedEx-FRMC@alpa.org'],
};

const listSteps =
  [
    { text: 'Contact the company.', defaultOpen: true, caption: 'Contact CRS Immediately', note: '1-844-495-1049', popoverText: '(paraphrasing CBA 12.A.9). A pilot who becomes excessively tired (fatigued) shall notify CRS immediately and speak with the Duty Officer about their situation. If this happens during a trip and the decision is made to remove you from the balance of the trip, the trip will “end” in that city. Note: fatigue in base, during a hub turn (no legal rest between trips,) is also treated the same way.' },
    { text: 'ARRANGE for rest', caption: 'Work with DO and Flight Services', note: 'GT and hotel', popoverText: 'Work with the DO and Flight Services Desk (FSD) to arrange Ground Transportation and hotel for recovery.' },
    { text: 'REST', caption: 'Priority is Rest', popoverText: 'DO NOT make travel arrangements until you have RESTED and RECOVERED.' },
    { text: 'MAKE ARRANGEMENTS for RTB', caption: 'Deviate after coordination', popoverText: 'If in the field, after rest, work with DO, CRS, GT and Flight Services to deadhead back to base. Request an Established Fare Letter from the DO. After the required changes, only then can the crewmember deviate and make personal arrangements (Pairing will only display activity up to fatigue call, nothing after.)' },
    { text: 'AFTER ACTION FATIGUE REPORT', caption: 'File a fatigue report', note: 'File a DART', popoverText: 'The Company email sent to you will have a direct link. Secondary access is available via the PFC Report link, where you will find your uncompleted report generated by the Duty Officer. Link: pilot.fedex.com/fem/#/myevents . Please do not create a new report.' },
  ];

const accordionItems = listSteps.map(step => ({ label: step.text, defaultOpen: step.defaultOpen, content: step.popoverText }));

</script>
